/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import * as path from "path";
import { existsSync, mkdirSync, readFileSync } from "fs";
import { strict as assert } from "assert";
import {
    AcceptanceCondition,
    BaseFuzzTestState,
    createWeightedGenerator,
    Generator,
    generatorFromArray,
    interleave,
    makeRandom,
    performFuzzActions,
    Reducer,
    SaveInfo,
    take,
} from "@fluid-internal/stochastic-test-utils";
import {
    MockFluidDataStoreRuntime,
    MockContainerRuntimeFactory,
    MockStorage,
} from "@fluidframework/test-runtime-utils";
import { IChannelServices } from "@fluidframework/datastore-definitions";
import { SharedString } from "../sharedString";
import { IntervalCollection, IntervalType, SequenceInterval } from "../intervalCollection";
import { SharedStringFactory } from "../sequenceFactory";

interface FuzzTestState extends BaseFuzzTestState {
    containerRuntimeFactory: MockContainerRuntimeFactory;
    sharedStrings: SharedString[];
}

interface ClientSpec {
    stringId: string;
}

interface RangeSpec {
    start: number;
    end: number;
}

interface IntervalCollectionSpec {
    collectionName: string;
}

interface AddText extends ClientSpec {
    type: "addText";
    index: number;
    content: string;
}

interface RemoveRange extends ClientSpec, RangeSpec {
    type: "removeRange";
}

// For non-interval collection fuzzing, annotating text would also be useful.

interface AddInterval extends ClientSpec, IntervalCollectionSpec, RangeSpec {
    type: "addInterval";
    // Normally interval ids get autogenerated, but including it here allows tracking
    // what happened to an interval over the course of its lifetime based on the history
    // file, which is useful for debugging test failures.
    id: string;
}

interface ChangeInterval extends ClientSpec, IntervalCollectionSpec, RangeSpec {
    type: "changeInterval";
    id: string;
}

interface DeleteInterval extends ClientSpec, IntervalCollectionSpec {
    type: "deleteInterval";
    id: string;
}

interface Synchronize {
    type: "synchronize";
}

type IntervalOperation = AddInterval | ChangeInterval | DeleteInterval;

type TextOperation = AddText | RemoveRange;

type ClientOperation = IntervalOperation | TextOperation;

type Operation = ClientOperation | Synchronize;

// Note: none of these options are currently exercised, since the fuzz test fails with pretty much
// any configuration due to known bugs. Once shared interval collections are in a better state these
// should be revisited.
interface OperationGenerationConfig {
    /**
     * Maximum length of the SharedString (locally) before no further AddText operations are generated.
     * Note due to concurency, during test execution the actual length of the string may exceed this.
     */
    maxStringLength?: number;
    /**
     * Maximum number of intervals (locally) before no further AddInterval operations are generated.
     * Note due to concurency, during test execution the actual number of intervals may exceed this.
     */
    maxIntervals?: number;
    maxInsertLength?: number;
    intervalCollectionNamePool?: string[];
    validateInterval?: number;
}

const defaultOptions: Required<OperationGenerationConfig> = {
    maxStringLength: 1000,
    maxIntervals: 100,
    maxInsertLength: 10,
    intervalCollectionNamePool: ["comments"],
    validateInterval: 100,
};

// A few places in the fuzz testing code need to inspect existing collections on a SharedString
// to determine where to insert/modify/delete an interval from. There's some logic to scope all
// provided labels with "intervalCollections/", which is what the iterator returns. This works
// around that.
function* getUnscopedLabels(string: SharedString): Iterable<string> {
    const prefix = "intervalCollections/";
    for (const label of string.getIntervalCollectionLabels()) {
        assert(label.startsWith(prefix));
        yield label.substring(prefix.length);
    }
}

function makeOperationGenerator(optionsParam?: OperationGenerationConfig): Generator<Operation, FuzzTestState> {
    const options = { ...defaultOptions, ...(optionsParam ?? {}) };
    type ClientOpState = FuzzTestState & { sharedString: SharedString; };

    function isNonEmpty(collection: IntervalCollection<SequenceInterval>): boolean {
        for (const _ of collection) {
            return true;
        }

        return false;
    }

    // All subsequent helper functions are generators; note that they don't actually apply any operations.
    function position({ random, sharedString }: ClientOpState): number {
        return random.integer(0, sharedString.getLength() - 1);
    }

    function exclusiveRange(state: ClientOpState): RangeSpec {
        const start = position(state);
        const end = state.random.integer(start + 1, state.sharedString.getLength());
        return { start, end };
    }

    function inclusiveRange(state: ClientOpState): RangeSpec {
        const start = position(state);
        const end = state.random.integer(start, state.sharedString.getLength() - 1);
        return { start, end };
    }

    function nonEmptyIntervalCollection({ sharedString, random }: ClientOpState): string {
        const nonEmptyLabels = Array.from(getUnscopedLabels(sharedString)).filter((label) => {
            const collection = sharedString.getIntervalCollection(label);
            return isNonEmpty(collection);
        });
        return random.pick(nonEmptyLabels);
    }

    function interval(state: ClientOpState): { collectionName: string; id: string; } {
        const collectionName = nonEmptyIntervalCollection(state);
        const intervals = Array.from(state.sharedString.getIntervalCollection(collectionName));
        return {
            collectionName,
            id: state.random.pick(intervals).getIntervalId(),
        };
    }

    function addText(state: ClientOpState): AddText {
        const { random, sharedString } = state;
        return {
            type: "addText",
            index: position(state),
            content: random.string(random.integer(0, options.maxInsertLength)),
            stringId: sharedString.id,
        };
    }

    function removeRange(state: ClientOpState): RemoveRange {
        return { type: "removeRange", ...exclusiveRange(state), stringId: state.sharedString.id };
    }

    function addInterval(state: ClientOpState): AddInterval {
        return {
            type: "addInterval",
            ...inclusiveRange(state),
            collectionName: state.random.pick(options.intervalCollectionNamePool),
            stringId: state.sharedString.id,
            id: state.random.uuid4(),
        };
    }

    function deleteInterval(state: ClientOpState): DeleteInterval {
        return {
            type: "deleteInterval",
            ...interval(state),
            stringId: state.sharedString.id,
        };
    }

    function changeInterval(state: ClientOpState): ChangeInterval {
        return {
            type: "changeInterval",
            ...interval(state),
            ...inclusiveRange(state),
            stringId: state.sharedString.id,
        };
    }

    const hasAnInterval = ({ sharedString }: ClientOpState): boolean =>
        Array.from(getUnscopedLabels(sharedString)).some((label) => {
            const collection = sharedString.getIntervalCollection(label);
            return isNonEmpty(collection);
        });

    const lengthSatisfies = (criteria: (length: number) => boolean): AcceptanceCondition<ClientOpState> =>
        ({ sharedString }) => criteria(sharedString.getLength());
    const hasNonzeroLength = lengthSatisfies((length) => length > 0);
    const isShorterThanMaxLength = lengthSatisfies((length) => length < options.maxStringLength);

    const hasNotTooManyIntervals: AcceptanceCondition<ClientOpState> = ({ sharedString }) => {
        let intervalCount = 0;
        for (const label of getUnscopedLabels(sharedString)) {
            for (const _ of sharedString.getIntervalCollection(label)) {
                intervalCount++;
                if (intervalCount >= options.maxIntervals) {
                    return false;
                }
            }
        }
        return true;
    };

    const and = <T>(...clauses: AcceptanceCondition<T>[]): AcceptanceCondition<T> =>
        (t: T) => clauses.reduce<boolean>((prev, cond) => prev && cond(t), true);

    const clientBaseOperationGenerator = createWeightedGenerator<Operation, ClientOpState>([
        [addText, 2, isShorterThanMaxLength],
        [removeRange, 1, hasNonzeroLength],
        [addInterval, 2, and(hasNotTooManyIntervals, hasNonzeroLength)],
        [deleteInterval, 2, hasAnInterval],
        [changeInterval, 2, and(hasAnInterval, hasNonzeroLength)],
    ]);

    const clientOperationGenerator = (state: FuzzTestState) =>
        clientBaseOperationGenerator({ ...state, sharedString: state.random.pick(state.sharedStrings) });

    return interleave(
        clientOperationGenerator,
        () => ({ type: "synchronize" }),
        options.validateInterval,
    );
}

function runIntervalCollectionFuzz(
    generator: Generator<Operation, FuzzTestState>,
    initialState: FuzzTestState,
    saveInfo?: SaveInfo,
    loggingInfo?: { intervalId: string, clientIds: string[] }
): void {
    // Validates that all shared strings in the provided array are consistent in the underlying text
    // and location of all intervals in any interval collections they have.
    function assertConsistent(sharedStrings: SharedString[]): void {
        const first = sharedStrings[0];
        for (const other of sharedStrings.slice(1)) {
            assert.equal(first.getLength(), other.getLength());
            assert.equal(
                first.getText(),
                other.getText(),
                `Non-equal text between strings ${first.id} and ${other.id}.`,
            );
            const firstLabels = Array.from(getUnscopedLabels(first)).sort();
            const otherLabels = Array.from(getUnscopedLabels(other)).sort();
            assert.deepEqual(
                firstLabels,
                otherLabels,
                `Different interval collections found between ${first.id} and ${other.id}.`,
            );
            for (let i = 0; i < firstLabels.length; i++) {
                const collection1 = first.getIntervalCollection(firstLabels[i]);
                const collection2 = other.getIntervalCollection(otherLabels[i]);
                const intervals1 = Array.from(collection1);
                const intervals2 = Array.from(collection2);
                assert.equal(
                    intervals1.length,
                    intervals2.length,
                    `Different number of intervals found in ${first.id} and ${other.id}` +
                    ` at collection ${firstLabels[i]}`,
                );
                for (const interval of intervals1) {
                    const otherInterval = collection2.getIntervalById(interval.getIntervalId());
                    const firstStart = first.localRefToPos(interval.start);
                    const otherStart = other.localRefToPos(otherInterval.start);
                    assert.equal(firstStart, otherStart,
                        `Startpoints of interval ${interval.getIntervalId()} different:\n` +
                        `\tfull text:${first.getText()}\n` +
                        `\tclient ${first.id} char:${first.getText(firstStart, firstStart + 1)}\n` +
                        `\tclient ${other.id} char:${other.getText(otherStart, otherStart + 1)}`);
                    const firstEnd = first.localRefToPos(interval.end);
                    const otherEnd = other.localRefToPos(otherInterval.end);
                    assert.equal(firstEnd, otherEnd,
                        `Endpoints of interval ${interval.getIntervalId()} different:\n` +
                        `\tfull text:${first.getText()}\n` +
                        `\tclient ${first.id} char:${first.getText(firstEnd, firstEnd + 1)}\n` +
                        `\tclient ${other.id} char:${other.getText(otherEnd, otherEnd + 1)}`);
                    assert.equal(interval.intervalType, otherInterval.intervalType);
                    assert.deepEqual(interval.properties, otherInterval.properties);
                }
            }
        }
    }

    // Small wrapper to avoid having to return the same state repeatedly; all operations in this suite mutate.
    // Also a reasonable point to inject logging of incremental state.
    const statefully =
        <T>(statefulReducer: (state: FuzzTestState, operation: T) => void): Reducer<T, FuzzTestState> =>
            (state, operation) => {
                if (loggingInfo !== undefined) {
                    console.log("Operation to be applied:", JSON.stringify(operation, undefined, 4));
                    for (const id of loggingInfo.clientIds) {
                        const sharedString = state.sharedStrings.filter(s => s.id === id)[0];
                        const collection = sharedString.getIntervalCollection("comments"); // TODO: bad assumption here
                        const interval = collection.getIntervalById(loggingInfo.intervalId);
                        console.log(`Client ${id}:`);
                        if (interval !== undefined) {
                            const start = sharedString.localReferencePositionToPosition(interval.start);
                            const end = sharedString.localReferencePositionToPosition(interval.end);
                            if (end === start) {
                                console.log(' '.repeat(start) + 'x');
                            } else {
                                console.log(' '.repeat(start) + '[' + ' '.repeat(end - start - 1) + ']');
                            }
                        }
                        console.log(sharedString.getText());
                        console.log('\n');
                    }
                    console.log('-'.repeat(20));
                }
                statefulReducer(state, operation);
                return state;
            };

    performFuzzActions(
        generator,
        {
            addText: statefully(({ sharedStrings }, { stringId, index, content }) => {
                const sharedString = sharedStrings.find((s) => s.id === stringId);
                sharedString.insertText(index, content);
            }),
            removeRange: statefully(({ sharedStrings }, { stringId, start, end }) => {
                const sharedString = sharedStrings.find((s) => s.id === stringId);
                sharedString.removeRange(start, end);
            }),
            addInterval: statefully(({ sharedStrings }, { stringId, start, end, collectionName, id }) => {
                const sharedString = sharedStrings.find((s) => s.id === stringId);
                const collection = sharedString.getIntervalCollection(collectionName);
                collection.add(start, end, IntervalType.SlideOnRemove, { intervalId: id });
            }),
            deleteInterval: statefully(({ sharedStrings }, { stringId, id, collectionName }) => {
                const sharedString = sharedStrings.find((s) => s.id === stringId);
                const collection = sharedString.getIntervalCollection(collectionName);
                collection.removeIntervalById(id);
            }),
            changeInterval: statefully(({ sharedStrings }, { stringId, id, start, end, collectionName }) => {
                const sharedString = sharedStrings.find((s) => s.id === stringId);
                const collection = sharedString.getIntervalCollection(collectionName);
                collection.change(id, start, end);
            }),
            synchronize: statefully(({ containerRuntimeFactory, sharedStrings }) => {
                containerRuntimeFactory.processAllMessages();
                assertConsistent(sharedStrings);
            }),
        },
        initialState,
        saveInfo,
    );
}

const directory = path.join(__dirname, "../../src/test/results");

// Once known issues with SharedInterval are fixed, a small set of fuzz tests with reasonably-tuned parameters
// should be enabled.
describe.only("IntervalCollection fuzz testing", () => {
    before(() => {
        if (!existsSync(directory)) {
            mkdirSync(directory);
        }
    });

    function runTests(seed: number, generatorArg?: Generator<Operation, FuzzTestState>): void {
        it(`with default config, seed ${seed}`, async () => {
            const numClients = 3;
            const filepath = path.join(directory, `${seed}.json`);

            const containerRuntimeFactory = new MockContainerRuntimeFactory();
            const sharedStrings = Array.from({ length: numClients }, (_, index) => {
                const dataStoreRuntime = new MockFluidDataStoreRuntime();
                const sharedString = new SharedString(
                    dataStoreRuntime,
                    String.fromCharCode(index + 65),
                    SharedStringFactory.Attributes,
                );
                const containerRuntime = containerRuntimeFactory.createContainerRuntime(dataStoreRuntime);
                const services: IChannelServices = {
                    deltaConnection: containerRuntime.createDeltaConnection(),
                    objectStorage: new MockStorage(),
                };

                sharedString.initializeLocal();
                sharedString.connect(services);
                return sharedString;
            });

            const generator = generatorArg ?? take(30, makeOperationGenerator({ validateInterval: 10 }));

            const initialState: FuzzTestState = {
                sharedStrings,
                containerRuntimeFactory,
                random: makeRandom(seed),
            };

            runIntervalCollectionFuzz(
                generator,
                initialState,
                { saveOnFailure: true, filepath },
                { intervalId: "91d2ec3c-c120-4c12-8bfe-d8bf645acfd0", clientIds: ["A", "B", "C"] }
            );
        });
    }

    function replayTestFromFailureFile(seed: number) {
        const filepath = path.join(directory, `${seed}.json`);
        let generator: Generator<Operation, FuzzTestState>
        try {
            generator = generatorFromArray<any, any>(JSON.parse(readFileSync(filepath).toString()));
        } catch (err: any) {
            // Mocha executes skipped suite creation blocks, but whoever's running this suite only cares if
            // the containing block isn't skipped. Report the original error to them from inside a test.
            if (err.message.includes("ENOENT")) {
                it(`with default config, seed ${seed}`, () => {
                    throw err;
                });
                return;
            }
            throw err;
        }

        runTests(seed, generator);
    }

    const testCount = 30000;
    for (let i = 0; i < testCount; i++) {
        runTests(i);
    }

    // Change this seed and unskip the block to replay the actions from JSON on-disk.
    // This can be useful for quickly minimizing failure json while attempting to root cause.
    describe.only("replay specific seed", () => {
        const seedToReplay = 15605;
        // const seedToReplay = 2536;
        replayTestFromFailureFile(seedToReplay);
    })

    // TODO: regression tests for:
    /**
     * 414, idea was bad skip "don't need to change interval" when comparison didn't take into account rebasing
     * [
    {
        "type": "addText",
        "index": 0,
        "content": "ABCDEFGH",
        "stringId": "B"
    },
    {
        "type": "addText",
        "index": 0,
        "content": "XYZ",
        "stringId": "A"
    },
    {
        "type": "addInterval",
        "start": 4,
        "end": 4,
        "collectionName": "comments",
        "stringId": "B",
        "id": "1c742683-c2ed-4c2e-bfa0-cffa40290474"
    },
    {
        "type": "changeInterval",
        "collectionName": "comments",
        "id": "1c742683-c2ed-4c2e-bfa0-cffa40290474",
        "start": 7,
        "end": 7,
        "stringId": "B"
    },
    {
        "type": "synchronize"
    }
]

3330, demonstrates why can't just use "isRemoved" on getSlideToSegment:

[
    {
        "type": "addText",
        "index": 0,
        "content": "qYkQWWR4eaKG04Tlw-uk",
        "stringId": "B"
    },
    {
        "type": "synchronize"
    },
    {
        "type": "removeRange",
        "start": 17,
        "end": 20,
        "stringId": "A"
    },
    {
        "type": "addInterval",
        "start": 14,
        "end": 17,
        "collectionName": "comments",
        "stringId": "B",
        "id": "e6b4c739-d7eb-4d7e-bf67-bbf69dece12b"
    },
    {
        "type": "addText",
        "index": 15,
        "content": "0Julo1v",
        "stringId": "A"
    },
    {
        "type": "removeRange",
        "start": 8,
        "end": 17,
        "stringId": "C"
    },
    {
        "type": "synchronize"
    }
]

4956, demonstrates why even locally you can't trust that you don't need to apply a change op:
     */
});
